"""
版权所有 2024 AI星图

根据 Apache License, Version 2.0（“许可证”）授权；
除非遵守许可证，否则你不能使用此文件。
你可以在以下网址获得许可证副本：

    http://www.apache.org/licenses/LICENSE-2.0

除非适用法律要求或书面同意，根据许可证分发的软件按“原样”提供，
不提供任何明示或暗示的担保或保证。
请参阅许可证以了解管理权限和限制的特定语言。

附加条款：
- 本作品的副本可以自由复制和分发，但不得进行修改、衍生或演绎。
- 如需转载或其他用途，必须事先获得 AI星图权利人的书面许可。

---

Copyright 2024 AI星图

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Additional Terms:
- Copies of this work may be freely copied and distributed, but modification, derivation, or adaptation is not allowed.
- For any form of redistribution or other use, prior written permission from the copyright holder, AI

"""
# -*- coding: utf-8 -*-
"""AI星图-孙悟空大模型数字分身

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0YmTLLKaBebvEykvGrEiAG0ySQ5L7FM

**欢迎来到AI星图**


我是齐天大圣孙悟空!欢迎来到AI星图。本期课程,我们介绍大模型TTS模型,超级悟空、打造数字人分身。

本期课程，我们将基于视频开头您听到的“猴哥”解说,介绍如何对TTS模型进行微调, 并生成特定人物音色, 实现数字人分身的效果。

## 大模型数字人分身

### 1. TTS模型
- **模型训练推理框架**
  - **[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS)**: 探讨GPT-SoVITS框架在TTS模型训练和推理中的应用。

### 2. 收集素材
- **高质量素材**
  - **高人声质量**: 确保素材具有清晰、纯净的声音，减少噪音。
  - **去除杂音、背景音**: 通过后期处理去除录音中的杂音和背景音。

### 3. 打标
- **语音切割**
  - **不宜过长**: 确保每段语音片段长度适中，便于模型处理。
  - **确保精确表达**: 切割后的语音应能准确传达信息。
- **语音文字对齐**: 通过工具将语音与文本进行对齐，确保文字内容与语音一致。
- **校对文本**: 对文本内容进行校对，确保无误。
- **增加标点符号，支持停顿**: 在文本中添加标点符号，以支持语音生成时的自然停顿。

### 4. 微调
- **输出微调后的模型**: 完成微调后,输出经过优化的TTS模型。

### 5. 推理
- **输入**:
  - 示例输入文本: "我是齐天大圣孙悟空!欢迎来到AI星图。本期课程,我们介绍大模型TTS模型,超级悟空、打造数字人分身。"
- **输出**:
  - 语音文件格式: `wav`, `mp3`

### 6.引用
- 特别感谢  [GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS) 项目团队的卓越贡献



### 结语

本期视频做到这里，欢迎大家点赞关注、收藏和转发。欢迎加入我们的社群，本期课程涉及到的代码，我会放到视频下方的链接。

谢谢大家的观看！
"""