"""
版权所有 2024 AI星图

根据 Apache License, Version 2.0（“许可证”）授权；
除非遵守许可证，否则你不能使用此文件。
你可以在以下网址获得许可证副本：

    http://www.apache.org/licenses/LICENSE-2.0

除非适用法律要求或书面同意，根据许可证分发的软件按“原样”提供，
不提供任何明示或暗示的担保或保证。
请参阅许可证以了解管理权限和限制的特定语言。

附加条款：
- 本作品的副本可以自由复制和分发，但不得进行修改、衍生或演绎。
- 如需转载或其他用途，必须事先获得 AI星图权利人的书面许可。

---

Copyright 2024 AI星图

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Additional Terms:
- Copies of this work may be freely copied and distributed, but modification, derivation, or adaptation is not allowed.
- For any form of redistribution or other use, prior written permission from the copyright holder, AI

"""
# -*- coding: utf-8 -*-
"""AI星图-本地构建AI智能体
发布时间: 2024-08-18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjQzMC5rxpGLaf46u1JrQSrtDlJ2Si71

**欢迎来到AI星图**

本期课程中，我们将系统性地介绍AI的知识体系，并通过编排AI智能体，深入探索和学习AI领域的核心概念和应用方法。

## AI知识体系介绍

### 1. 大语言模型（LLM）
- **语言模型Language**
  - **GPT-4o**: 深入理解GPT-4o模型的架构和应用场景。
  - **LLaMA 3.1开源**: 探讨LLaMA 3.1的开源模型、相关论文及其在实际应用中的价值。
  - **Qwen2**: 最新Qwen2模型的特性及优化技巧。
- **Embedding**
  - **BCE（网易有道）**: 了解网易有道的BCE模型及其应用。
  - **BGE（智源研究院）**: 探讨智源研究院的BGE模型及其在文本表示中的优势。
- **ReRanker**
  - **二次重排序**: 学习如何使用ReRanker提升搜索结果的相关性。
- **Audio**
  - **语音转文字（STT）**
    - **Whisper**: 掌握Whisper在语音转文字中的应用。
  - **文字转语音（TTS）**: 探讨文字转语音技术及其应用场景。
- **Image**
  - **SD3**: 深入学习Stable Diffusion 3的生成技术。
- **Video**
  - **Sora**: 了解Sora在视频生成中的前沿应用。

### 2. LLM推理引擎
- **Xinference**: 探讨Xinference引擎及其在推理中的应用。
- **Ollama**: 掌握Ollama推理引擎的高级功能和应用案例。

### 3. 提示词Prompt Engineering
- **指定任务**: 学习如何通过提示词指定任务并引导模型完成特定操作。
- **优化意图**: 掌握提示词优化技巧，提升模型输出的准确性。
- **提供上下文**: 了解在生成过程中如何提供有效的上下文信息。
- **限定输出**: 探讨如何限定模型输出的格式和内容。

### 4. 本地知识
- **大模型微调（Finetune）**
  - **Dataset数据集**
    - **高质量语料**: 探讨如何构建和使用高质量语料库进行模型微调。
    - **语料清洗**: 学习语料清洗技术，提升数据集的质量。
- **RAG（Retrieval-Augmented Generation）**
  - **文档处理**
    - **转换**: 学习如何将多种文档格式转换为模型可读格式。
    - **分割Chunk**
      - **LLM**: 了解如何对文档进行语义分割以优化LLM处理。
      - **语义分割**: 学习语义分割技术在文本处理中的应用。
      - **Max Length**: 探讨控制分割长度的最佳实践。
  - **Embedding**
    - **BCE/BGE**: 深入理解BCE和BGE模型在RAG中的应用。
  - **ReRanker**: 学习如何结合ReRanker提升RAG的效果。
  - **Search**
    - **搜索引擎**
      - **互联网搜索**: 学习互联网搜索技术及其在RAG中的应用。
      - **本地搜索**: 了解如何在本地构建高效的搜索系统。
  - **GraghRAG**
    - **Global全局视角**
      - **时间/地点/人物/事件**: 学习如何构建和分析全局视角下的知识图谱。
    - **Local局部视角**: 探讨局部视角在知识图谱中的应用。

### 5. 智能体Agent
- **低代码AI-Factory**
  - **Flowise开源**: 探索Flowise在低代码开发中的应用。
  - **Dify开源**: 学习Dify开源项目的使用和优化。
  - **Coze字节跳动**: 了解Coze在低代码开发中的应用案例。
- **Workflow**: 探讨智能体工作流的设计与实现。
- **Tools**
  - **Python**: 学习如何使用Python开发智能体工具。
  - **HTTP-API**: 了解如何通过HTTP-API与智能体进行交互。


---


# AI星图智能体

## 1. 选择基座模型
- **gpt-4o-mini**
- **llama3.1-8b**

## 2. 安装LLM推理引擎
- **Ollama**
- **Xinference**

## 3. 准备知识库RAG
- **Embedding**
- **ReRanker**
- **准备数据集**
  - **AI星图视频集**

## 4. 本地安装Dify
- **Workflow工作流**
  - **获取旅游景点列表**
- **Tools**
  - **当前时间**
  - **周计算**

## 5. Q/A
- **介绍一下AI星图**
- **AI星图视频总共出了多少期？简单介绍一下。**
- **视频做完了。下周三开始休假5天，请根据当前时间，生成一个北京的旅游计划。**
"""